### PR TITLE
Rework api

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Builds on #8. Makes log construction significantly easier. I couldn't get the trait bounds right for the `femme::with_filter` function; we should add that in a follow-up PR. thanks!

## Examples
```rust
use kv_log_macro as log;

fn main() {
    femme::with_level(femme::LevelFilter::Trace);
    log::error!("Buffer has to be 16 bytes in length");
    log::warn!("Unauthorized access attempt", { route: "/login", user_id: "827756627", });
    log::info!("Server listening", { port: "8080" });
    log::info!("Request handled", { method: "GET", path: "/foo/bar", status: 200, elapsed: "4ms" });
    log::debug!("Getting String as bson value type");
    log::trace!("Task spawned", {task_id: "567", thread_id: "12"});
}
```

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Actually I think we should remove these traits. closing!

**Comment by yoshuawuyts** [comment]
wooooooops

**Comment by yoshuawuyts** [comment]
@lrlna I don't think #10 requires any API changes so we can implement it after we merge this. The current version of femme has the same performance profile as what we're proposing in this patch so it's not even a regression.

**Comment by yoshuawuyts** [comment]
@lrlna oh, also important: we need new screenshots for the new major!

**Comment by lrlna** [comment]
@yoshuawuyts yes, I will take a screenshot on my system :D

**Comment by kyrias** [comment]
I just tried that example with femme 2.0.1 and kv-log-macro 1.0.5, and the trace line isn't actually getting logged.  Not sure how to debug that further though.

**Comment by kyrias** [comment]
@yoshuawuyts This seems to be due to kv-log-macro hard-coding the max level to Debug: https://github.com/yoshuawuyts/kv-log-macro/blob/b9c16cef570bd080906e03c1b791ca2903c7806a/src/lib.rs#L33

Is this intentional?  Or would it be possible to instead use the `STATIC_MAX_LEVEL` exposed by the `log` crate, since it has features for setting that which people might be using.

**Pull request merged**
