### PR TITLE
Wasm

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Retrying https://github.com/lrlna/femme/pull/2. Accidentally closed the PR, and wasn't allowed to recreate. Anyway, adds wasm support to `femme`!

## Kv logging
Not super happy with the kv logging output, but also don't want to spend any more time getting `console.table` hooked up. This should be a decent enough midway for now I hope. Thanks!

## Screenshots
2019-08-04-235500_1920x1080

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Another fun future improvement is using [`Symbol.toStringTag`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag) to change the way the associated object is displayed in the console.

Not needed if we go down the `console.table` path tho, but probably good to keep in mind.

**Comment by lrlna** [comment]
I think what would interesting to do next is offer and ndjson logger that could be passed down to wasm as well when running in production.

The things I am not sure about is how the `env` set in JS can be read and passed down to the wasm target. Maybe that's not at all possible, but if it is, would be keen to implement that next!

**Comment by lrlna** [comment]
📦 `1.2.0`

**Comment by yoshuawuyts** [comment]
> The things I am not sure about is how the env set in JS can be read and passed down to the wasm target. Maybe that's not at all possible, but if it is, would be keen to implement that next!

Could you say more about this? It sounds like you'd like to be able to switch between two different outputs in WASM? If I'm understanding you correctly then the way we do this for the server would also work here. E.g. use `if cfg!(debug_assertions) {}` to swap between output modes, and determine which one to use based on whether `--release` is passed to `cargo build`.

**Comment by lrlna** [comment]
Will try to clarify:

Let's say I have a module that uses `femme`. This module is then published under the `--release` tag, but gets used in a JS app either in `NODE_ENV=development` or `NODE_ENV=production` depending on the stage of development this app is at. Depending on the two modes we either get `console.log`s, or log to whatever the production logging provider is at. I think what I am proposing will most likely require two builds, which will probably affect bundle size.

I think what you've suggested works well for when you just link a local WASM package to your local JS app, which is already really quite helpful!

**Comment by yoshuawuyts** [comment]
@lrlna to my knowledge there's currently no standardized way to expose those vars in JS bundles -- it depends per bundler how it's done, and I don't think any of them keep a reference of it in the global namespace out of the box.

So a new module would need to be built on the JS side of things to set the global. And then another module would need to be built on the rust/wasm side to pick that up and read it out. I think that becomes a rather specific combination, at which point it might just make sense to just manually pick and choose what to display.

Does that make sense?

**Pull request merged**
